name: actions-workflow-manual-test
run-name: workflow manual trigger test
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Choice option(reason)'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Bolean option'
        required: false
        type: boolean
      customInput:
        description: 'Custom input'
        required: true
        type: string
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Custom input: $cusInput"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          cusInput: ${{ inputs.customInput }}
