name: testing content on push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Deploying to production server on branch $GITHUB_EVENT_COMMITS_MESSAGE"