name: testing content on push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "message ${{ github.event.commits.message }}"
      - name: Echo ref
        run: echo echo "Deploying to production server on branch $GITHUB_REF"