name: testing content on push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "message --> ${{ github.event.head_commit.message }}"
      - name: Echo email
        run: echo "email --> ${{ github.event.head_commit.author.email }}"

