name: testing content on push

on:
  workflow_call:

env:
  TEST_VAR: test_var

jobs:
  pyvariables:
    runs-on: ubuntu-latest
    env:
      test_secret: ${{ secrets.TEST_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: requirements
        run: |
          pip install -r workflowtesting/requirements.txt
      - name: set pythonpath
        run: |
          echo "PYTHONPATH=${PYTHONPATH}:${HOME}/${{github.event.repository.name}}" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
      - name: Run py on pr
        env:
            USER_EMAIL: ${{ github.event.head_commit.author.email }}
            USERNAME: ${{ github.event.head_commit.author.username }}
            DESCRIPTION: ${{ github.event.head_commit.message }}
            REPO: ${{ github.repository }}
        run: |
          python workflowtesting/scripts/gh_variables.py

      - name: what is X on pr
        run: echo ${{ github.repository }}

      - name: Sets env vars for release
        run: |
          echo "VARIABLE=some_variable" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: Testing secret - correct
        if: env.test_secret == 'TEST'
        run: echo "Secret test successful"

      - name: Testing secret - empty
        if: env.test_secret == ''
        run: echo "Secret test empty"

  print_context:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ toJSON(github) }}
