name: testing content on push

on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
        with:
          repository: Holub-Jan/test-repo
          token: ${{ secrets.GHTOKEN }}

