name: testing content on push

on:
  workflow_call:
    inputs:
      token:
        required: false
        type: string

jobs:
  pyvariables:
    runs-on: ubuntu-latest
    env:
      INPUT_TOKEN: ${{ inputs.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: requirements
        run: |
          pip install -r requirements.txt
      - name: set pythonpath
        run: |
          echo "PYTHONPATH=${PYTHONPATH}:${HOME}/${{github.event.repository.name}}" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
      - name: Run py on pr
        run: |
          python  scripts/gh_variables.py

      - name: what is X on pr
        run: echo "${GITHUB_WORKSPACE}"
