name: testing content on push

on:
  workflow_call:

jobs:
  pyvariables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Save variables and run
        env:
          USER_EMAIL: ${{ github.event.head_commit.author.email }}
          USERNAME: ${{ github.event.head_commit.author.username }}
          DESCRIPTION: ${{ github.event.head_commit.message }}
        run: python gh_variables.py

