name: testing content on push

on:
  workflow_call:

env:
  TEST_VAR: test_var

jobs:
  pyvariables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: requirements
        run: |
          pip install -r requirements.txt
      - name: set pythonpath
        run: |
          echo "PYTHONPATH=mlprepare" >> $GITHUB_PATH
          echo "$PATH"
      - name: Run py on pr
        env:
            USER_EMAIL: ${{ github.event.head_commit.author.email }}
            USERNAME: ${{ github.event.head_commit.author.username }}
            DESCRIPTION: ${{ github.event.head_commit.message }}
            REPO: ${{ github.repository }}
        run: |
          python scripts/gh_variables.py

      - name: what is X on pr
        run: echo ${{ github.repository }}

      - name: Sets env vars for release
        run: |
          echo "VARIABLE=some_variable" >> $GITHUB_ENV
        if: github.event_name == 'push'

  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
