name: testing content on push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo email
        run: echo 'Email ${{ github.event.commits.committer.email }}'
      - name: Echo ref
        run : echo 'Message ' $GITHUB_REF
      - name: Echo ref
        run: echo 'Message ' ${{ GITHUB_REF }}