name: testing content on push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo context
        run: echo 'Email ${{ github.event.commits.committer.email }}'
             echo 'Message ${{ github.event.commits.message }}'